[platformio]
default_envs = master

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:master]
board = esp32-s3-devkitc-1
build_src_filter = +<main.cpp>
lib_deps = ESP32-audioI2S
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
# 注：板子 PSRAM 为 OCT(八线) 版，预编译 arduino 核仅支持 QUAD，无法启用，故不设 PSRAM

[env:slave_s3]
board = esp32-s3-devkitc-1
build_src_filter = +<slave_s3.cpp>
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB

[env:test_i2s_s3]
board = esp32-s3-devkitc-1
build_src_filter = +<test_i2s_s3.cpp>
board_build.flash_mode = qio
board_build.f_cpu = 240000000L

[env:test_bt_s3]
board = esp32-s3-devkitc-1
build_src_filter = +<test_bt_s3.cpp>
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
