[platformio]
default_envs = master

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:master]
board = esp32dev
build_src_filter = +<main.cpp>
lib_deps = ESP32-audioI2S

[env:slave_c3]
board = esp32-c3-devkitm-1
build_src_filter = +<slave_c3.cpp>
board_build.flash_mode = dio
board_build.f_cpu = 160000000L

[env:test_i2s_c3]
board = esp32-c3-devkitm-1
build_src_filter = +<test_i2s_c3.cpp>
board_build.flash_mode = dio
board_build.f_cpu = 160000000L

[env:test_pwm_c3]
board = esp32-c3-devkitm-1
build_src_filter = +<test_pwm_c3.cpp>
board_build.flash_mode = dio
board_build.f_cpu = 160000000L

[env:test_i2s_s3]
board = esp32-s3-devkitc-1
build_src_filter = +<test_i2s_s3.cpp>
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
